language: ruby

rvm: [2.2.2]
#python: [2.7]

#addons:
  #apt:
    #packages:
    # fetch Ghostscript to optimize/minimize the PDF, if > 5MB
    #- ghostscript

cache:
  apt: true
  #directories:    
    #- $HOME/.cache/pip

install:
  # install optional dependencies for asccidoctor-diagram
  - sudo apt-get -qq update && sudo apt-get install -y ditaa graphviz
  - travis_retry _travis/install_plantuml.sh
  # install AsciiDoctor
  - gem install asciidoctor
  # PDF generator
  - gem install --no-ri --no-rdoc --pre asciidoctor-pdf
  # syntax highlighter
  - gem install --no-ri --no-rdoc coderay pygments.rb
  # diagram support
  - gem install --no-ri --no-rdoc asciidoctor-diagram
  # optionally install more diagram tools: blockdiag, seqdiag, actdiag and nwdiag
  #- pip install --user blockdiag actdiag seqdiag nwdiag
  #- pip install --user shaape
  - gem install slim tilt haml
  # AsciiDoctor Stylesheet Factory - Dependencies
  - gem install --version '0.12.7' compass --no-ri --no-rdoc
  - gem install --version '4.3.2' zurb-foundation --no-ri --no-rdoc
  # AsciiDoctor Stylesheet Factory
  - wget https://github.com/asciidoctor/asciidoctor-stylesheet-factory/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - cd asciidoctor-stylesheet-factory-master
  #- ./build-stylesheet.sh colony.css
  - compass compile
  - cp -pr stylesheets ../user-manual/
  - cp -pr stylesheets ../developer-manual/
  - cd ..  
  # Copy Images
  - mkdir -p user-manual/images
  - cp -p images/* user-manual/images

before_script:
  - asciidoctor --version
  - asciidoctor-pdf --version
  #- asciidoctor-diagram --version
  - ls -alF

script:
  # create user-manual
  - asciidoctor -a stylesheet=../stylesheets/foundation.css -a icons=font -a source-highlighter=highlightjs -a toc=left -a linkcss -a toclevels=3 -a revnumber=1.0+$TRAVIS_TAG user-manual/en/book.adoc -o user-manual/en/index.html -v
  #- asciidoctor -r asciidoctor-pdf -b pdf -a pdf-stylesdir=pdf -a pdf-style=wpnxm -a pdf-fontsdir=pdf/fonts -a revnumber=$TRAVIS_TAG user-manual/en/book.adoc -o user-manual/en/book.pdf -v
  # create developer-manual
  - asciidoctor -r asciidoctor-diagram -a stylesheet=../stylesheets/foundation.css -a icons=font -a source-highlighter=highlightjs -a toc=left -a linkcss -a toclevels=3 -a revnumber=1.0+$TRAVIS_TAG developer-manual/en/book.adoc -o developer-manual/en/index.html -v
  #- asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf -a pdf-stylesdir=pdf -a pdf-style=wpnxm -a pdf-fontsdir=pdf/fonts -a revnumber=$TRAVIS_TAG developer-manual/en/book.adoc -o developer-manual/en/book.pdf -v
  # create an index entry page for the website @ http://fifengine.github.io/docs/
  - asciidoctor README.adoc -o index.html -v
  # apply PDF document optimizations
  #- ./bin/optimize-pdf user-manual/en/book.pdf
  #- ./bin/optimize-pdf developer-manual/en/book.pdf
  - ls -alF user-manual
  - ls -alF developer-manual
  # cleanup (remove folders before commiting to gh-pages)
  - rm -r asciidoctor-stylesheet-factory-master/
  #- rm -r pdf/

after_success:
  - ./publish.sh  

env:
  global:
    - secure: "MhTp1CehTA33/EmjsjduomQfo9YTuIPA4FVTwhLfA2UtikcGblkzD8gcyeb30e0Xpieu6mZHLuCPDGBlVC/MfcPeYhTWowhf3KEB+uIlwktQBQmU04GBM98+eP2PhPrRgNbfqv7cKOMEv7jZ9THGxdZoUMJclZE1PVqhlLhy6r6RpZsdqA1EjFwO5G+elK/Ss+mvJ/rgbX71BVPSLO43fRAdoZMnH/Dv3wPr/CtmV9VoDXGwE/QzVa9O6O11A22OCKxXHMiaB1HYzT2zug+1j/ucIYoggjODoN1dk0EjAuAISmhg+VqiiF91FKjCTdUJABESgsEzffRtYYS8EWky7bkGHWrfzeWISrWZg1UA2mXRAEkVqHvySt/E2/XWWZnokyDPEg6ApnFGW8Id7mfcUCAu14iIQQE718iYAxSNk0U+gIdAbXuFMlTb8v1qNQ0cBiC5uppGo4UqDVCW/ckyhLiBpYooGaLmWA8qCMmQyiM4FnO3ZrGe+CynYBmkWefmm4aR4rQ81C3tCbJglbDR03SGuqC44JFnhRBcArV398rA2S03dC0v9dUaaf/sRx0P/9P1vzSXlNmGrI+8iXEBsrRK7yOoqA8qbBioVgw/3ttw+RniQBvSW7kMh5q5YwkJzPf5rbs/VU0Pl88FOIOZMDu1R2tKzx25YeTKwkySFnA="
git:
  depth: 10
